### ISSUE TITLE
Generating costmap using object detection data

### ISSUE THREAD

**Issue by ragingonyx** [gt-marine-robotics-group/Virtuoso#6]
As part of our mapping server, we want to have the ability to generate a costmap, detailing where the vehicle can or cannot go. This can be accomplished either by using built in nav2 functions or created in house by iteratively marking points on a grid using the object detections and increasing confidence at each time step. We can also attempt to leverage SLAM to get this information by generating occupancy grids which serve a similar purpose to costmaps.

Here are some useful links:
[SLAM](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html) using Nav2 tutorial
[STVL](https://navigation.ros.org/tutorials/docs/navigation2_with_stvl.html), which is a voxel filter plugin for pointclouds but publishes a costmap 
[Occupancy Grids](https://towardsdatascience.com/occupancy-grid-mapping-with-webots-and-ros2-a6162a644fab)

**Comment by PotentialError** [comment]
Subteam Meeting:
[costmap_2d::Costmap2DROS](http://library.isr.ist.utl.pt/docs/roswiki/costmap_2d.html)
Current understanding, when you create a cost_map2d, ROS "creates a node in the background", which receives PointCloud and/or LaserScan info. To setup the source of the data, cost_map2d has parameters to set the string name of the "observation_sources" (ex. lidar) and the topic name from which the observation source will post its data. The cost_map publishes the determined occupied, free, and unknown cells as nav_msgs/GridCells.

Questions:
Do we already know what the namespaces that we’re taking in PointCloud data from?
Does the LIDAR namespace automatically publish as a PointCloud, or do we have to worry about doing that ourselves?
How does the voxel_grid topic of the costmap_2d related to STVL?
How do we pass in parameters (such as observation_sources) in a node’s operation, rather than in the command line?

Objectives:
Test with fake/empty sensor namespaces to test our understanding of inputting parameters into the costmap_2d backend node.
Try to make a custom node which subscribes to the costmap's publisher topics and stores that data in GridCells.

**Comment by TigerPeng2** [comment]
Whenever I have time after my linear midterm, I think I'm just going to spin up a node with just a costmap in it and see what the node structure looks like. Because I understand how to access the parameters of a node that we write ourselves, but if it's a background node that ROS generates, I don't know how to change that in the code itself, rather than with dynamic reconfigure, as you mentioned.

Do we assume the node is created immediately at runtime and we can configure it before the robot starts moving?

**Comment by ragingonyx** [comment]
The node is created at runtime and it can be configured at any time and the parameters can be found through a combination of rostopic echo and ros param get. The tutorial for STVL should mention a yaml file that contains all the parameters in there. I would recommend looking in there first.

**Comment by PotentialError** [comment]
Added basic boilerplate code that generates a basic costmap using a default parameter file and launch file without the use of STVL.

**Comment by PotentialError** [comment]
**Current costmap progress:**
Understanding:
After downloading the Nav2 library, to create a costmap make a launch file that runs the nav2_costmap_2d pkg feeding in a yaml file that follows the yaml format found in costmap nav2 documentation: https://navigation.ros.org/configuration/packages/configuring-costmaps.html#example
Current work:
 - Test to see if our dummy costmap yaml and launch file work by either using turtlesim provided by nav2 or creating dummy data through a rosbag (data recorder)
  - Figure out how to implement the STVL plugin using the github build into the costmap
